//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn schema_name(&self) -> Option<&str> {
        Some("public")
    }
    fn table_name(&self) -> &str {
        "privatekey"
    }
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveModel, DeriveActiveModel, Serialize)]
// #[sea_orm(table_name = "user")]
pub struct Model {
    // #[sea_orm(primary_key)]
    pub public_key: String,
    // #[sea_orm(unique)]
    pub private_key: String,  // The "sub" value returned by Google
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    PublicKey,
    PrivateKey,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    PublicKey,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }

}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    PublicKey,
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::PublicKey => Entity::belongs_to(super::user::Entity)
                .from(Column::PublicKey)
                .to(super::user::Column::PublicKey)
                .into(),
        }
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicKey.def()
    }
}

impl ColumnTrait for Column {
    type EntityName = Entity;

    fn def(&self) -> ColumnDef {
        match self {
            Self::PublicKey => ColumnType::String(None).def(),
            Self::PrivateKey => ColumnType::String(None).def().unique(),
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}
